version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - RUBY_DEBUG_OPEN=true
      - HISTFILE=/app/.bash_history
      - EDITOR=vim
    stdin_open: true
    tty: true
    command: ./bin/dev

volumes:
  bundle:
  node_modules:
